""" Constants"""
MAX_RATING = 5

LODGING=1
PETROL_PUMP=2
EATING_PLACE=3

AMENITIES = {
    'LODGING': LODGING,
    'PETROL_PUMP': PETROL_PUMP,
    'EATING_PLACE':EATING_PLACE
}

AMENITIES_CHOICES=[
    (LODGING, "Lodging"),
    (PETROL_PUMP, "Petrol Pump"),
    (EATING_PLACE, "Eating Place"),
]

HATCHBACK=1
SEDAN=2
SUV=3
SEDAN_PREMIUM=4
SEDAN_BUSINEESS=5
LUXURY=6

VEHICLE_TYPES = {
    'HATCHBACK': HATCHBACK,
    'SEDAN': SEDAN,
    'SUV': SUV,
    'SEDAN_PREMIUM': SEDAN_PREMIUM,
    'SEDAN_BUSINEESS': SEDAN_BUSINEESS,
    'LUXURY':LUXURY
}

VEHICLE_TYPES_CHOICES = {
    (HATCHBACK, "HATCHBACK"),
    (SEDAN, "SEDAN"),
    (SUV, "SUV"),
    (SEDAN_PREMIUM, "SEDAN - PREMIUM"),
    (SEDAN_BUSINEESS, "SEDAN - BUSINEESS CLASS"),
    (LUXURY, "LUXURY")
}
