# Generated by Django 2.1.8 on 2019-05-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('streams', '0003_auto_20190522_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('details', models.TextField(help_text='Add place details')),
                ('duration_of_visit', models.CharField(max_length=100)),
                ('distance_from_start_location', models.IntegerField(default=0)),
                ('map_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
