# Generated by Django 2.1.8 on 2019-05-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20190531_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceDetail',
        ),
    ]
